# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\tessUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_tessUI(object):
    def setupUi(self, tessUI):
        tessUI.setObjectName("tessUI")
        tessUI.resize(1065, 565)
        self.centralwidget = QtWidgets.QWidget(tessUI)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setEnabled(True)
        self.label.setGeometry(QtCore.QRect(-30, -30, 1101, 601))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("Black_Template.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.button = QtWidgets.QLabel(self.centralwidget)
        self.button.setGeometry(QtCore.QRect(340, 110, 351, 331))
        self.button.setText("")
        self.button.setPixmap(QtGui.QPixmap("Siri_1.gif"))
        self.button.setScaledContents(True)
        self.button.setObjectName("button")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(460, 410, 121, 51))
        self.label_3.setStyleSheet("background-color: rgb(0, 85, 255);\n"
"color: rgb(255, 255, 255);\n"
"font: 20pt \"MS Shell Dlg 2\";\n"
"font: 11pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(85, 255, 255);\n"
"color: rgb(85, 0, 0);\n"
"\n"
"")
        self.label_3.setObjectName("label_3")
        tessUI.setCentralWidget(self.centralwidget)

        self.retranslateUi(tessUI)
        QtCore.QMetaObject.connectSlotsByName(tessUI)

    def retranslateUi(self, tessUI):
        _translate = QtCore.QCoreApplication.translate
        tessUI.setWindowTitle(_translate("tessUI", "MainWindow"))
        self.label_3.setText(_translate("tessUI", "      START"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    tessUI = QtWidgets.QMainWindow()
    ui = Ui_tessUI()
    ui.setupUi(tessUI)
    tessUI.show()
    sys.exit(app.exec_())
